### ISSUE TITLE
loved the contribution skyline , did you do it with the generator https://skyline.github.com/ ?

### ISSUE THREAD

**Issue by AmyLovelace** [ppizarror/ppizarror#1]
i asked you bcouse mine´s not working 

greeting fellow developer.

**Comment by ppizarror** [comment]
Hi Amy, I did not use skyline, but this repo https://github.com/yoshi389111/github-profile-3d-contrib. You can also customize the action,

greetings

**Comment by ppizarror** [comment]
Also, I prefer static ones instead of dynamic ones because, in some cases, SVG keyframes fail to detect the window context and only update if the canvas is updated. But that is up to yours,

**Comment by AmyLovelace** [comment]
thank you so much i will give it a try <3
